version: '3.8'
services:
  gateway:
    build: gateway/Dockerfile
    image: docker_gateway
    container_name: docker_gateway
    ports:
      - "8080:8080"
    depends_on:
    - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server/Dockerfile
    image: docker_server
    container_name: docker_server
    ports:
      - "9090:9090"
    depends_on:
     - db
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=8888

  db:
    image: postgres:13.7-alpine
    container_name: shareit-postgres
    ports:
      - "8888:5432"
    environment:
        - POSTGRES_DB=shareit
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
